manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tap0119
      url-base: https://github.com/tap0119
  projects:
    - name: zmk
      remote: tap0119
      revision: main
      import: app/west.yml
  self:
    path: config

#manifest:
#  remotes:
#    - name: zmkfirmware
#      url-base: https://github.com/zmkfirmware
#  projects:
#    - name: zmk
#      remote: zmkfirmware
#      revision: main
#      import: app/west.yml
#  self:
#    path: config
